# Generated by Django 4.2.13 on 2024-06-27 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_delivery_address_user_telephone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='telephone',
            new_name='phone_number',
        ),
    ]
