# Generated by Django 4.2.13 on 2024-06-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_telephone_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, verbose_name='Номер телефона'),
        ),
    ]
