# Generated by Django 4.2.13 on 2024-06-19 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Цена'),
        ),
    ]
