# Generated by Django 4.2.13 on 2024-06-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discount',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Скидка в %'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Цена'),
        ),
    ]
